# Generated by Django 5.2.8 on 2025-11-30 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='fan',
            field=models.CharField(choices=[('Python', 'Python Backend'), ('Frontend', 'Frontend (React)'), ('English', 'English Language'), ('SMM', 'SMM & Marketing')], default='Python', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='tolov_qildi',
            field=models.BooleanField(default=False),
        ),
    ]
